### PR TITLE
Improve the handling of incorrect coveralls token

### PR DESCRIPTION
**Pull request by rorygraves**

### CODE REVIEW

**Comment by rorygraves** [comment]
Ha - I fix the tests on travis - and promptly fail to run test tests before submitting ;).  That will teach me.

**Comment by fommil** [comment]
LGTM @rorygraves did you want to pull this before @sksamuel makes the release?

**Comment by rorygraves** [comment]
Yep @sksamuel  A build when you have a chance would be good.

**Comment by fommil** [comment]
and please ping us when it is disted, so we can update ensime :smile:

**Pull request merged**
