### PR TITLE
Fix windows support

### PR DESCRIPTION
**Pull request by mdedetrich**
Resolves: https://github.com/scoverage/sbt-coveralls/issues/294

This PR makes coveralls works under windows, it consists of 2 commits

* `Make tests portable so it runs on Windows`: Various changes to tests so that they can run properly on Windows (but no changes to core codebase)
* `Add windows support by removing POSIX line seperator normalization`: Actual changes to core codebase so that sbt-coveralls can run under windows plus adding windows to github actions CI for verification

The changes that needed to be done to tests are fairly mechanical (largely involving handling Windows file separators) with notable changes listed below
* Shell scripts (`generate.sh`/`prepare.sh`) have been replaced with equivalent implementations in build.sbt sbt's dsl which provides us Windows portability for free
* Windows equivalent xml template files (i.e. `.xml.template`) has been introduced as `.xml.windows.template`. The only difference is using `\` instead of `/`, there might have been smarter solutions to this but I kept it this way to keep it simple.

In regards to the actual fix, this involved removing the so called normilzations which involved replacing the Windows file separator with the POSIX one. I am not sure what the original intent of these "normalizations" were, but making all representations/serializations of paths consistently use `\` under Windows (and `/` under POSIX although this behaviour is unchanges) fixes all of the issues.

The only current issue is that the [ `ninesstack.nmesos.cli.CliSpec`](https://github.com/NinesStack/nmesos/blob/trunk/src/test/scala/ninesstack/nmesos/cli/CliSpec.scala#L20-L25) scripted sbt-test [fails](https://github.com/scoverage/sbt-coveralls/actions/runs/10886410611/job/30206347056?pr=323#step:6:199) because this external scala project itself doesn't appear to be portable on Windows. I don't know what the best course of action here is as that repo is external to this one, simplest solution might be to just update that project so that the test passes under windows which will automatically fix it here.

### CODE REVIEW

**Comment by mdedetrich** [comment]
@rolandtritsch The PR is ready albeit there is one issue (mentioned in description).

**Comment by rolandtritsch** [comment]
Hi Matthew. This week I am on vacation. Will take a look at this next week.
- RT

**Comment by rolandtritsch** [comment]
https://github.com/scoverage/sbt-coveralls/actions/runs/10886410611/job/30206347056?pr=323#step:6:118

Hi @mdedetrich. The windows test fails. Any idea what might be wrong here?

**Comment by mdedetrich** [comment]
> https://github.com/scoverage/sbt-coveralls/actions/runs/10886410611/job/30206347056?pr=323#step:6:118
> 
> Hi @mdedetrich. The windows test fails. Any idea what might be wrong here?

Yes, I said so why in the original post of the PR

> The only current issue is that the [ `ninesstack.nmesos.cli.CliSpec`](https://github.com/NinesStack/nmesos/blob/trunk/src/test/scala/ninesstack/nmesos/cli/CliSpec.scala#L20-L25) scripted sbt-test [fails](https://github.com/scoverage/sbt-coveralls/actions/runs/10886410611/job/30206347056?pr=323#step:6:199) because this external scala project itself doesn't appear to be portable on Windows. I don't know what the best course of action here is as that repo is external to this one, simplest solution might be to just update that project so that the test passes under windows which will automatically fix it here.

**Comment by rolandtritsch** [comment]
Hi Matthew. For now let's just remove the nmesos test.

---
***@***.***/+353-86-8563976
Thumb-powered. Excuse the curtness.

**Comment by mdedetrich** [comment]
> Hi Matthew. For now let's just remove the nmesos test.

Sure thing, I'll do this on Sunday when I get back from vacation.

**Comment by mdedetrich** [comment]
@rolandtritsch I have removed the `nmesos` test as instructed and everything is passing now

**Comment by rolandtritsch** [comment]
Hi @mdedetrich. Merged and published. Thanks for the fix. - https://github.com/scoverage/sbt-coveralls/releases/tag/v1.3.14

**Pull request merged**
