### PR TITLE
Configurable Git Repository Location

### PR DESCRIPTION
**Pull request by stephen-lazaro**
Probably the simplest way to resolve  https://github.com/scoverage/sbt-coveralls/issues/54. I didn't end up needing it but maybe someone else would like it. I tested it with the directory ".." and it worked fine, was able to build and push coverage.
Adds SettingKey for git respository location
Makes GitClient initialize to key value else "."

### CODE REVIEW

**Comment by randreucetti** [comment]
Any plans to get this merged ?

**Comment by stephen-lazaro** [comment]
I'm going to close this in three months unless someone prompts. I'm happy to rebase and clean this, but there certainly needs to be some feedback from the project owners beforehand.

**Comment by iphydf** [comment]
@sksamuel can this be merged and released?

**Comment by sksamuel** [comment]
@stephen-lazaro thanks, I've merged it now.

**Pull request merged**
