### PR TITLE
Fix various bugs with aggregated projects

### PR DESCRIPTION
**Pull request by fommil**
Might result in config problems for some users, but since 1.0.0 hasn't been released yet, I think it's a good trade-off for the increased stability.

### CODE REVIEW

**Comment by fommil** [comment]
that failed because I don't think the tests were running on travis before. I didn't touch the code that's failing.

**Comment by fommil** [comment]
@sksamuel is there any chance you could publish a jar when this is merged by rory?

**Comment by rorygraves** [comment]
@fommil I think I know why the tests are failing - looking at it.
Changes look good.

**Comment by fommil** [comment]
it would be good if @sksamuel added his sonatype creds here and we got snapshots building from travis.

**Pull request merged**
